### ISSUE TITLE
我用了，更卡了

### ISSUE THREAD

**Issue by MCredbear** [QianyeGroup/K20P75Hz_Installer#1]
用了之后，内核报的刷新率的确是变了，但问题是应用好像都只能跑在41fps了（不管是75hz还是81hz），而且屏幕有一块横着的区域的dpi变得不正常（变大了应该是），文字什么的到了这块区域就会变小一点

**Comment by RealHeart** [comment]
仅支持9.7.11以下

**Comment by MCredbear** [comment]
> 
> 
> 仅支持9.7.11以下

那为什么新版不能用了，有研究过吗？
